flaskr/models.py
from sqlalchemy import Column, Integer
from sqlalchemy.orm import declarative_base
from sqlalchemy_easy_softdelete.hook import IgnoredTable
from sqlalchemy_easy_softdelete.mixin import generate_soft_delete_mixin_class
from sqlalchemy.inspection import inspect
from . import db
from sqlalchemy.sql import func
from werkzeug.security import generate_password_hash, check_password_hash
from flask import url_for
from sqlalchemy_serializer import SerializerMixin
import json
from datetime import datetime
import locale
locale.setlocale(locale.LC_TIME, "id_ID")


# Create a Class that inherits from our class builder

class SoftDeleteMixin(generate_soft_delete_mixin_class(
    # This table will be ignored by the hook
    # even if the table has the soft-delete column
    ignored_tables=[IgnoredTable(table_schema="public", name="cars"),]
)):
    # type hint for autocomplete IDE support
    deleted_at: datetime


# Apply the mixin to your Models
Base = declarative_base()


class Gizi(db.Model, SerializerMixin, SoftDeleteMixin):
    __tablename__ = "gizi"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text, nullable=False)
    age = db.Column(db.Integer, nullable=False)
    gender = db.Column(db.Boolean, nullable=False)
    born_weight = db.Column(db.Double, nullable=False)
    born_height = db.Column(db.Double, nullable=False)
    weight = db.Column(db.Double, nullable=False)
    height = db.Column(db.Double, nullable=False)
    status = db.Column(db.Text, nullable=False)

    def serialize(self):
        return {
            "id": self.id,
            "name": self.name,
            "age": self.age,
            "gender": self.gender,
            "born_weight": self.born_weight,
            "born_height": self.born_height,
            "weight": self.weight,
            "height": self.height,
            "status": self.status,
        }


class Models(db.Model, SerializerMixin, SoftDeleteMixin):
    __tablename__ = "models"
    id = db.Column(db.Integer, primary_key=True)
    loss = db.Column(db.Text, nullable=False)
    alpha = db.Column(db.Double, nullable=False)
    max_iter = db.Column(db.Integer, nullable=False)
    testsize = db.Column(db.Double, nullable=True, default=0)
    accuracy = db.Column(db.Double, nullable=True, default=0)
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now())
    learning_at = db.Column(db.DateTime(timezone=True), server_default=None)

    def serialize(self):
        return {
            "id": self.id,
            "loss": self.loss,
            "alpha": self.alpha,
            "max_iter": self.max_iter,
            "testsize": self.testsize,
            "accuracy": self.accuracy,
            "created_at": self.created_at,
            "learning_at": self.learning_at
        }


class Results(db.Model, SerializerMixin, SoftDeleteMixin):
    __tablename__ = "results"
    id = db.Column(db.Integer, primary_key=True)
    model_id = db.Column(db.Integer, db.ForeignKey("models.id"))
    fold = db.Column(db.Integer, nullable=True)
    actual = db.Column(db.Text, nullable=True)
    predicted = db.Column(db.Text, nullable=True)

    def serialize(self):
        return {
            "id": self.id,
            "model_id": self.model_id,
            "fold": self.fold,
            "actual": self.actual,
            "predicted": self.predicted,
        }

flaskr/__init__.py
import os

from functools import wraps
from flask import Flask, render_template, redirect, flash, url_for, current_app, request
from flask_sqlalchemy import SQLAlchemy
from flaskr.config import Config

db = SQLAlchemy()

def create_app(config_class=Config):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(Config)
    db.init_app(app)

    from .views import views
    from .api import api

    @app.errorhandler(404)
    def not_found(e):
        return render_template("404.html"), 404

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(api, url_prefix="/api")

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from .models import Gizi, Results, Models

    return app

flaskr/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from .models import Gizi
from . import db

views = Blueprint("views", __name__)


@views.route("/")
def index():
    return render_template(
        "page/index.html",
        page="dashboard",
    )


@views.route("/home")
def home():
    return render_template(
        "page/index.html",
        page="dashboard",
    )

@views.route("/gizi")
def gizi():
    return render_template(
        "page/gizi.html",
        page="gizi",
    )

@views.route("/model")
def model():
    return render_template(
        "page/model.html",
        page="model",
    )

@views.route("/prediksi")
def prediksi():
    return render_template(
        "page/prediksi.html",
        page="prediksi",
    )

flaskr/templates/layout/panel-meta.html
<small>Klasifikasi Gizi Menggunakan Metode SGD &#174 2024</small>

flaskr/templates/layout/panel-navbar.html
<a href="{{ url_for('views.home') }}" data-page="dashboard" class="page-nav"><i class="material-icons">home</i>
    <span>Beranda</span></a>
<a href="{{ url_for('views.gizi') }}" data-page="gizi" class="page-nav"><i class="material-icons">source</i> <span>Data
        Gizi</span></a>
<a href="{{ url_for('views.model') }}" data-page="model" class="page-nav"><i class="material-icons">account_tree</i> <span>Learning
        Model</span></a>
<a href="{{ url_for('views.prediksi') }}" data-page="prediksi" class="page-nav"><i class="material-icons">science</i>
    <span>Prediksi</span></a>

flaskr/templates/layout/panel.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SGD</title>
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/png">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dt/datatables.min.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/materialize.min.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css')}}" />
    {% block style %}{% endblock %}
</head>

<body>
    <div class="page-wrapper">
        <div class="page-box">
            <div class="page-nav-wrapper">
                {% include 'layout/panel-navbar.html' %}
            </div>
            <div class="page-content">
                {% block content %}{% endblock %}
            </div>
            <div class="page-meta center">
                {% include 'layout/panel-meta.html' %}
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/jquery-3.7.1.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/chart.umd.js')}}"></script>
    <script src="{{ url_for('static', filename='js/swal.js')}}"></script>
    <script src="{{ url_for('static', filename='dt/datatables.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/materialize.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/utils/puller.js')}}"></script>
    <script src="{{ url_for('static', filename='js/moment.js')}}"></script>
    <script src="{{ url_for('static', filename='js/moment-timezone.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"
        integrity="sha512-d8F1J2kyiRowBB/8/pAWsqUl0wSEOkG5KATkVV4slfblq9VRQ6MyDZVxWl2tWd+mPhuCbpTB4M7uU/x9FlgQ9Q=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        const baseUrl = "";
        let page = "{{ page }}";
        const cloud = new Puller();
    </script>
    <script src="{{ url_for('static', filename='js/main.js')}}"></script>
    {% block script %}{% endblock %}
</body>

</html>

flaskr/templates/page/gizi.html
{% extends "layout/panel.html" %}
{% block content %}
<br>
<div class="row">
    <div class="col s12 center">
        <a class="waves-effect waves-light btn green btn-slider" data-target="form" data-action="add"><i
                class="material-icons left">add</i>Tambah</a>
    </div>
</div>
<div class="row">
    <div class="col s12">
        <table class="striped highlight responsive-table" id="table-gizi" style="width:100%">
            <thead>
                <tr>
                    <th>Nama</th>
                    <th>Gender</th>
                    <th>Usia</th>
                    <th>Berat Badan</th>
                    <th>Tinggi Badan</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<div class="page-slider" data-page="form">
    <div class="slider-nav">
        <a class="waves-effect waves-light btn orange btn-slider-close"><i
                class="material-icons left">arrow_back</i>Kembali</a>
    </div>
    <div class="slider-content">
        <form action="#!" method="POST">
            <input type="hidden" name="id" value="">
            <div class="row">
                <div class="col s12 m6 offset-m3">
                    <div class="row">
                        <div class="input-field s12">
                            <input id="name" name="name" type="text" class="validate" required>
                            <label for="name">Nama Balita</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <input id="age" name="age" type="number" class="validate" min="0" required>
                            <label for="age">Usia (Bulan)</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <select name="gender">
                                <option value="" disabled selected>Pilih Jenis Kelamin</option>
                                <option value="true">Laki-laki</option>
                                <option value="false">Perempuan</option>
                            </select>
                            <label>Jenis Kelamin</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <input id="born_weight" name="born_weight" type="number" class="validate" min="0.1"
                                step="0.1" required>
                            <label for="born_weight">Berat Badan Lahir (Kg)</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <input id="born_height" name="born_height" type="number" class="validate" min="0.1"
                                step="0.1" required>
                            <label for="born_height">Tinggi Badan Lahir (Cm)</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <input id="weight" name="weight" type="number" class="validate" min="0.1" step="0.1"
                                required>
                            <label for="weight">Berat Badan Periksa (Kg)</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <input id="height" name="height" type="number" class="validate" min="0.1" step="0.1"
                                required>
                            <label for="height">Tinggi Badan Periksa (Cm)</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <select name="status">
                                <option value="" disabled selected>Pilih Status Gizi</option>
                                <option value="Gizi Buruk">Gizi Buruk</option>
                                <option value="Gizi Kurang">Gizi Kurang</option>
                                <option value="Gizi Baik">Gizi Baik</option>
                                <option value="Risiko Gizi Lebih">Beresiko Gizi Lebih</option>
                                <option value="Gizi Lebih">Gizi Lebih</option>
                                <option value="Obesitas">Obesitas</option>
                            </select>
                            <label>Distrik</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12 center">
                            <button class="btn waves-effect waves-light green darken-3" type="submit">Simpan</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='js/page/gizi.js') }}"></script>
{% endblock %}

flaskr/templates/page/index.html
{% extends "layout/panel.html" %}
{% block content %}
<br><br>
<div class="center">
    <small>Jumlah Data Learning</small>
    <h2 class="counter" id="total">0</h2>
</div>
<br>
<div class="row">
    <div class="col m6 s12">
        <div class="count-card">
            <p><i class="material-icons">man</i> Laki-Laki</p>
            <p class="number counter" id="man">0</p>
        </div>
    </div>
    <div class="col m6 s12">
        <div class="count-card">
            <p><i class="material-icons">woman</i> Perempuan</p>
            <p class="number counter" id="woman">0</p>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col s12">
        <canvas id="chart-status-1"></canvas>
    </div>
    <br><br>
    <div class="col s12 m6">
        <canvas id="chart-status-2"></canvas>
    </div>
    <div class="col s12 m6">
        <canvas id="chart-status-3" height="300px"></canvas>
    </div>
</div>
{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='js/page/dashboard.js') }}"></script>
{% endblock %}

flaskr/templates/page/model.html
{% extends "layout/panel.html" %}
{% block content %}
<br>
<div class="row">
    <div class="col s12 center">
        <a class="waves-effect waves-light btn green btn-slider" data-target="form" data-action="add"><i
                class="material-icons left">add</i>Tambah</a>
    </div>
</div>
<div class="row">
    <div class="col s12">
        <table class="striped highlight responsive-table" id="table-model" style="width:100%">
            <thead>
                <tr>
                    <th>Model Dibuat</th>
                    <th>Model Dilatih</th>
                    <th>Test Size / K-Fold</th>
                    <th>Akurasi</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<div class="page-slider" data-page="form">
    <div class="slider-nav">
        <a class="waves-effect waves-light btn orange btn-slider-close"><i
                class="material-icons left">arrow_back</i>Kembali</a>
    </div>
    <div class="slider-content">
        <form action="#!" method="POST">
            <div class="row">
                <div class="col s12 m6 offset-m3">
                    <div class="row">
                        <div class="input-field s12">
                            <select name="loss">
                                <option value="" disabled selected>Pilih Loss Function</option>
                                <option value="hinge">Hinge</option>
                                <option value="log_loss">Log loss</option>
                                <option value="modified_huber">Modified huber</option>
                                <option value="squared_hinge">Squared hinge</option>
                                <option value="perceptron">Perceptron</option>
                                <option value="squared_error">Squared error</option>
                                <option value="huber">Huber</option>
                                <option value="epsilon_insensitive">Epsilon insensitive</option>
                                <option value="squared_epsilon_insensitive">Squared epsilon insensitive</option>
                            </select>
                            <label>Distrik</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <input id="alpha" name="alpha" type="number" class="validate" min="0.0001" step="0.0001"
                                required>
                            <label for="alpha">Learning Rate</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <input id="max_iter" name="max_iter" type="number" class="validate" min="1" step="1"
                                required>
                            <label for="max_iter">Itereasi Maksimal</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12">
                            <input id="testsize" name="testsize" type="number" class="validate" min="0.1" step="0.1"
                                required>
                            <label for="testsize">Ukuran Data Testing / K-Fold</label>
                            <span class="helper-text">Gunakan angka desimal untuk merepresentasikan persentase data
                                testing atau gunakan angka bulat diatas 1 untuk menggunakan K-Fold</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field s12 center">
                            <button class="btn waves-effect waves-light green darken-3" type="submit">Simpan</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="page-slider" data-page="learning">
    <div class="slider-nav">
        <div class="progress">
            <div class="indeterminate"></div>
        </div>
    </div>
    <div class="slider-content">
        <div class="container model-loader">
            <img class="model-loader" src="{{ url_for('static', filename='img/loader/2.gif')}}" alt="loader">
            <br><br>
            <p class="model-loader"><em>Sedang Menjalankan Proses Pelatihan...</em></p>
        </div>
    </div>
</div>
<div class="page-slider" data-page="detail">
    <div class="slider-nav">
        <a class="waves-effect waves-light btn orange btn-slider-close"><i
                class="material-icons left">arrow_back</i>Kembali</a>
    </div>
    <div class="slider-content">
        <div class="row">
            <h4 class="center">
                Parameter
            </h4>
            <div class="col s12 m6 offset-m3">
                <table class="striped highlight responsive-table" id="parameter">
                    <tbody>
                        <tr>
                            <th>Loss Function</th>
                            <td>: <span class="loss"></span></td>
                        </tr>
                        <tr>
                            <th>Learning Rate</th>
                            <td>: <span class="alpha"></span></td>
                        </tr>
                        <tr>
                            <th>Iterasi Maksimal</th>
                            <td>: <span class="max_iter"></span></td>
                        </tr>
                        <tr>
                            <th>Test Size / K-Fold</th>
                            <td>: <span class="testsize"></span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br><br>
        <div class="row">
            <h4 class="center">Nilai Akurasi</h4>
            <div class="center">
                <small><em>(Akurasi tertinggi untuk penggunaan K-Fold)</em></small>
            </div>
            <h3 class="center"><span class="accuracy"></span></h3>
        </div>
        <br><br>
        <div class="row kfold hide">
            <h4 class="center">Hasil</h4>
            <div class="col s12 m8 offset-m2">
                <table>
                    <thead>
                        <tr>
                            <th>K-Fold</th>
                            <th>Prediksi Benar</th>
                            <th>Prediksi Salah</th>
                            <th>Total Data</th>
                            <th>Nilai Akurasi</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
        <div class="row tts hide">
            <h4 class="center">Hasil</h4>
            <div class="col s12 m8 offset-m2">
                <table>
                    <thead>
                        <tr>
                            <th>Testsize</th>
                            <th>Prediksi Benar</th>
                            <th>Prediksi Salah</th>
                            <th>Total Data</th>
                            <th>Nilai Akurasi</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    const loader_urls = [
        `{{ url_for('static', filename='img/loader/1.gif')}}`,
        `{{ url_for('static', filename='img/loader/2.gif')}}`,
    ]
    const loader_text = [
        `Sedang Menjalankan Proses Pelatihan...`,
        `Harap Bersabar...`,
        `Kami Jalankan Proses ini secara otomatis di belakang layar...`,
        `Nikmati kopi anda terlebih dahulu...`,
    ]
</script>
<script src="{{ url_for('static', filename='js/page/model.js') }}"></script>
{% endblock %}

flaskr/templates/page/prediksi.html
{% extends "layout/panel.html" %}
{% block content %}
<br>
<div class="nothing center hide">
    <img src="{{ url_for('static', filename='img/empty.png') }}" alt="nothing">
    <br><br>
    <h6><em>Anda Belum Melakukan Pelatihan Model</em></h6>
</div>
<div class="something hide">
    <div class="row">
        <div class="col s12 m6 offset-m3">
            <form action="#!" method="POST" id="predict">
                <div class="row">
                    <div class="input-field s12">
                        <select name="model_id">
                            <option value="" disabled selected>Pilih Model</option>
                            <option value="hinge">Hinge</option>
                            <option value="log_loss">Log loss</option>
                            <option value="modified_huber">Modified huber</option>
                        </select>
                        <label>Model</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field s12">
                        <input id="age" name="age" type="number" class="validate" min="0" required>
                        <label for="age">Usia (Bulan)</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field s12">
                        <select name="gender">
                            <option value="" disabled selected>Pilih Jenis Kelamin</option>
                            <option value="true">Laki-laki</option>
                            <option value="false">Perempuan</option>
                        </select>
                        <label>Jenis Kelamin</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field s12">
                        <input id="weight" name="weight" type="number" class="validate" min="0.1" step="0.1" required>
                        <label for="weight">Berat Badan Periksa (Kg)</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field s12">
                        <input id="height" name="height" type="number" class="validate" min="0.1" step="0.1" required>
                        <label for="height">Tinggi Badan Periksa (Cm)</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field s12 center">
                        <button class="btn waves-effect waves-light green darken-3" type="submit">Prediksi</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col s12 m6 offset-m3">
            <h4 class="center">Hasil Prediksi</h4>
            <hr>
            <h5 class="center"><em><span class="prediction"></span></em></h5>
        </div>
    </div>
</div>
<div class="page-slider" data-page="learning">
    <div class="slider-nav">
        <div class="progress">
            <div class="indeterminate"></div>
        </div>
    </div>
    <div class="slider-content">
        <div class="container model-loader">
            <img class="model-loader" src="{{ url_for('static', filename='img/loader/2.gif')}}" alt="loader">
            <br><br>
            <p class="model-loader"><em>Sedang Menjalankan Proses Pelatihan...</em></p>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    const loader_urls = [
        `{{ url_for('static', filename='img/loader/1.gif')}}`,
        `{{ url_for('static', filename='img/loader/2.gif')}}`,
    ]
    const loader_text = [
        `Sedang Menjalankan Proses Pelatihan...`,
        `Harap Bersabar...`,
        `Kami Jalankan Proses ini secara otomatis di belakang layar...`,
        `Nikmati kopi anda terlebih dahulu...`,
    ]
</script>
<script src="{{ url_for('static', filename='js/page/prediksi.js') }}"></script>
{% endblock %}